### ISSUE TITLE
Set up game such that it's synchronized across both players

### ISSUE THREAD

**Issue by Ennas** [belbeeno/trunk#13]
Currently the game is always synchronized as both operator and hostage have identical copies of the map and trunk, but should tasks #20, #21 and #22  be done, then we'll need to make sure that once the game starts:
- [ ] Buildings & Landmark positions are the same
- [ ] Buildings & Landmark size are the same
- [ ] Buildings & Landmark colors are the same
- [ ] Car paths should be synced or deterministic should cars be visible on the map

**Comment by kittychi** [comment]
@belbeeno is available for support if needed
